### ISSUE TITLE
Subtitles split

### ISSUE THREAD

**Issue by Tendaliu** [rany2/edge-tts#126] opened 2023-07-31 12:48 UTC
The segmentation of the subtitles is not very reasonable, a sentence is often cut off in the middle. Can you solve this problem?

**Comment by rany2** [comment] 2023-08-01 08:47
Yes, it is a solvable problem. Just haven't had the time to do

**Comment by rany2** [comment] 2023-08-01 08:48
I'll most likely use some SRT generation library instead of my "homegrown" solution to save time.

**Comment by rany2** [comment] 2023-08-12 14:45
Duplicate of https://github.com/rany2/edge-tts/issues/118

**Closed by rany2** 2023-08-12 14:45 UTC
Labels: good first issue
