### ISSUE TITLE
Service returns 403

### ISSUE THREAD

**Issue by FURYFOR** [rany2/edge-tts#265] opened 2024-10-18 11:23 UTC
File "C:\xxxx\lib\site-packages\aiohttp\client.py", line 947, in _ws_connect
raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=xxxxxxxxxxxxxxxxxx&ConnectionId=xxxxxxxxxxxxxxxxxxxx'

**Comment by LeeQixian** [comment] 2024-10-18 12:01
the same 403 here, and no help whether turn on or turn off the VPN tool.=-=

**Comment by joseph16388** [comment] 2024-10-18 12:02
the same!

**Comment by Raciel-c** [comment] 2024-10-18 12:03
gg

**Comment by rany2** [comment] 2024-10-18 12:09
It's weird because I don't have this issue on my end, I think it might be caused by some server maintenance.

**Comment by LeeQixian** [comment] 2024-10-18 12:17
maybe, but it's quite strange since i can normally use edge-tts service on my pad.
but the code just, 403. =-=

**Comment by houlin** [comment] 2024-10-18 12:23
你们墙国人，不会给api翻墙吗？？？？？？？？？？？？？？？？？

笑死了

**Comment by LeeQixian** [comment] 2024-10-18 12:29
> 你们墙国人，不会给api翻墙吗？？？？？？？？？？？？？？？？？
> 
> 笑死了

微软服务大部分在国内不是不会寄吗。=-=之前大声朗读除了偶尔抽风不也挺好的。

**Comment by galigaligo** [comment] 2024-10-18 13:03
还能回复吗

**Comment by galigaligo** [comment] 2024-10-18 13:03
还可以抢救一下吗

**Comment by LeeQixian** [comment] 2024-10-18 13:20
> > > 你们墙国人，不会给api翻墙吗？？？？？？？？？？？？？？？？？
> > > 笑死了
> > 
> > 
> > 微软服务大部分在国内不是不会寄吗。=-=之前大声朗读除了偶尔抽风不也挺好的。
> 
> 墙国总有人，看到免费的api，薅死羊毛，可劲儿的薅，大到微软都受不了了，不封你们封谁？

？所以就看到一个剩下的都是了是吧？哇会翻个墙翻出优越感了。

**Comment by LeeQixian** [comment] 2024-10-18 13:21
> 还可以抢救一下吗？ 我测试了edge浏览器的语音播报是正常的，估计还能抢救下把。

我手机上的语音播报也是正常的。
有需要的话电脑的梯子开tun模式看一下吧，我之前测了一下开tun没问题。

**Comment by goforu** [comment] 2024-10-18 14:13
支持cloudflare worker吗？

**Comment by rany2** [comment] 2024-10-18 14:20
Does it work from the Microsoft Edge browser? I don't have this issue on my end. If it doesn't work on Microsoft Edge as well, then I guess they are having server issues

**Comment by goforu** [comment] 2024-10-18 14:28
> Does it work from the Microsoft Edge browser? I don't have this issue on my end. If it doesn't work on Microsoft Edge as well, then I guess they are having server issues

In Mainland China, it's not working, while edge is working well

**Comment by rany2** [comment] 2024-10-18 14:33
OK, so the online TTS works in Edge.... but not edge-tts

**Comment by goforu** [comment] 2024-10-18 14:39
> OK, so the online TTS works in Microsoft Edge.... but not edge-tts

Exactly

**Comment by rany2** [comment] 2024-10-18 14:39
@goforu Does https://github.com/rany2/edge-tts/pull/268 fix it for you?

**Comment by rany2** [comment] 2024-10-18 14:43
I merged it, I don't have this issue myself but hopefully it fixes it for everyone else.

**Comment by LeeQixian** [comment] 2024-10-18 14:46
yes! it worked! the user agent is too old or , out-of-date i think? just modify this and the whole work again（）

**Comment by rany2** [comment] 2024-10-18 14:46
https://pypi.org/project/edge-tts/6.1.13/ released. Thanks @BG5T

**Closed** 2024-10-18 14:46 UTC

**Comment by houlin** [comment] 2024-10-18 16:27
This problem was manually set by Microsoft R&D (operation) personnel. Their goal was to ban (China region + plus a specific browser version number)

**Comment by rany2** [comment] 2024-10-18 17:59
> This problem was manually set by Microsoft R&D (operation) personnel. Their goal was to ban (China region + plus a specific browser version number)

That explains why I didn't face this issue. I'm not based in China. I suspected it was either a block that didn't propogate globally yet or some kind of regional thing. I guess it was the latter.

**Comment by czght** [comment] 2024-10-19 17:20
pip install edge-tts==6.1.13 更新到6.1.13，或者卸载再安装

**Comment by rany2** [comment] 2024-10-19 17:22
6.1.14 has a fix for list_voices so it's better to update to that.
