### ISSUE TITLE
The TrustedClientToken may be invalid or expired.

### ISSUE THREAD

**Issue by Heycys** [rany2/edge-tts#267] opened 2024-10-18 12:54 UTC
An error occurred: 403, message='Invalid response status', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=963f10d1abf9406c86fe4d60f75f0fca')

**Comment by rany2** [comment] 2024-10-18 14:18
Duplicate of https://github.com/rany2/edge-tts/issues/265

**Closed by rany2** 2024-10-18 14:18 UTC
