### ISSUE TITLE
Long text strings produce incomplete audio files

### ISSUE THREAD

**Issue by briankendall** [rany2/edge-tts#190] opened 2024-02-12 05:36 UTC
I'm trying to use edge-tts to convert a chapter of a book into an audiobook. It's about 39k characters and around 7500 words. When I run it through edge-tts, the resulting audio file is often incomplete. At what point in the text it cuts off seems to be inconsistent and arbitrary, and every now and then it successfully produces audio for the entire text.

Any idea what's going wrong? Is this even a use case that's expected to work? (I wonder if Microsoft is limiting how much audio it'll generate for one request.)

**Comment by rany2** [comment] 2024-02-15 18:31
I think it's related to an issue I've started encountering a month ago with the service randomly not respond with any audio data. It's a problem I've observed in the Edge browser as well.

I'm not sure how best to work around this but obviously a naive solution would be to retry a few times before accepting that the current split SSML doesn't have any audio data. Right now, if one of the split texts returns audio data; it doesn't raise an exception and considers it a success.

**Comment by rany2** [comment] 2024-02-16 20:00
Do you have any luck with the latest release (6.1.10)?

**Comment by rany2** [comment] 2024-02-16 22:06
Seems slightly better, but no luck. For context, I ran a generation 6 times on the a.txt file; there's about a megabyte or so missing...

```
➜  edge-tts git:(master) ✗ wc a.txt
  1738  40238 269540 a.txt
➜  edge-tts git:(master) ✗ ls -lh *.mp3
-rw-r--r-- 1 user user 87M Feb 17 00:02 a.mp3
-rw-r--r-- 1 user user 87M Feb 16 23:55 b.mp3
-rw-r--r-- 1 user user 85M Feb 17 00:03 c.mp3
-rw-r--r-- 1 user user 86M Feb 17 00:03 d.mp3
-rw-r--r-- 1 user user 87M Feb 17 00:02 e.mp3
-rw-r--r-- 1 user user 87M Feb 16 23:55 f.mp3
➜  edge-tts git:(master) ✗ ls -l *.mp3 
-rw-r--r-- 1 user user 90403632 Feb 17 00:02 a.mp3
-rw-r--r-- 1 user user 90403632 Feb 16 23:55 b.mp3
-rw-r--r-- 1 user user 88253712 Feb 17 00:03 c.mp3
-rw-r--r-- 1 user user 89767152 Feb 17 00:03 d.mp3
-rw-r--r-- 1 user user 90403632 Feb 17 00:02 e.mp3
-rw-r--r-- 1 user user 90403632 Feb 16 23:55 f.mp3
```

**Comment by expwise** [comment] 2024-02-19 03:55
6.1.10 stops running halfway through. I tested it with a 100,000-word text file and an MP3 with only around 80,000 words. However, 6.1.9 could run through the entire process. Yet, the subtitles generated by 6.1.9 only capture very little text.

**Comment by expwise** [comment] 2024-02-19 04:08
The text file contains 250,000 words, while both the MP3 and the subtitles consist of only around 80,000 words.
6.1.10:
![image](https://github.com/rany2/edge-tts/assets/48416454/205302e3-e13a-4714-8987-64294e58b65c)

**Comment by expwise** [comment] 2024-02-19 04:17
I remember previously the data for generating the MP3 would incrementally increase until completion, but now it goes from 0 directly to completion. I'm not sure if this is the reason for the issue.

**Comment by expwise** [comment] 2024-02-19 05:36
6.1.9:
![image](https://github.com/rany2/edge-tts/assets/48416454/aa8580f9-1107-4645-b8ea-7a08fd0e8691)

**Comment by rany2** [comment] 2024-02-19 13:21
@expwise Thanks for the info, I'll attempt a workaround in a bit. For the time being, I guess you'll need to stick to 6.1.9 as it works better somehow. It's worth mentioning that both have issues, it just seems like in your case 6.1.10 is worse.... 

My theory is that it has to do with the fact that 6.1.10 switches to the next chunk of ~64KiB text immediately without creating a new connection whereas 6.1.9 emulates the Microsoft Edge behavior of starting from a new connection.

**Comment by expwise** [comment] 2024-02-19 14:54
@rany2 Thank you for your efforts. Your project has been of great help to me. Well done!

**Comment by briankendall** [comment] 2024-03-22 13:34
What's the status of this issue? When I first reported it I was using 6.1.9.

**Comment by rany2** [comment] 2024-03-23 10:57
@briankendall It's more complicated than I expected, the issue is that sometimes their API returns audio output partially on the same connection. So I can't just have a check on whether the current connection returned any audio and if not, retry; it's more complicated....

**Comment by briankendall** [comment] 2024-03-23 12:41
@rany2 Understood! I hope you can figure out a method for working around this.

**Comment by lefnire** [comment] 2024-04-04 21:44
Maybe a workaround could be edge-tts to chunk text files into workable sizes, run them individually, then splice them back at the end?

**Comment by rany2** [comment] 2024-04-04 23:10
@lefnire we're doing that already, I tried different chunk sizes and I'm having the same issues regardless :(

**Comment by lefnire** [comment] 2024-04-05 00:07
@rany2 aw bummer. Thanks for the reply. I just went through the gamut: tortoise-tts, coqui-ai/tts, bark, edge-tts. Edge was victorious; but for this one bug. Tortoise is unusably slow (but great realism). Coqui & Bark can't take large files, nor did I find their voices realistic. edge-tts shocked me in terms of realism and speed. Here's hoping there's a solution somehow! Huge bummer Edge browser doesn't support to-file, without weird hoops (recording audio-out overnight kinda deal).

**Comment by rany2** [comment] 2024-04-05 00:16
@lefnire not sure what you mean by to-file but you could actually save the mp3: https://github.com/rany2/edge-tts/blob/e58af9da76c7c7ba101c955ee1c2e98ce424f58f/examples/basic_generation.py#L19

**Comment by lefnire** [comment] 2024-04-05 00:28
@rany2 right right, I meant it's a shame that Microsoft Edge Browser doesn't do this natively. Hence a big value-add of this project.

**Comment by rany2** [comment] 2024-05-17 09:10
@tschnibo Thanks for researching and your kind words, I didn't know `ClientSession` had a timeout and never actually faced any timeout errors so I don't think it's related to this issue specifically.  I'll try to look into your points to see if they get me any closer to a resolution.

It seems like the `timeout` value for `ClientSession` is a timeout for the entire operation, which seems like something we wouldn't want in this context because a generation might take a very long time. I'll most likely disable it all together and increase the receive_timeout to a minute.

**Comment by rany2** [comment] 2024-05-17 10:54
Can someone test if the version in master (not the one released in pypi) still has this issue?

**Comment by rany2** [comment] 2024-05-17 12:33
Nevermind it's still inconsistent when it comes to this, but the first few runs were fine. I got my hopes up when it was working the first couple runs ):

```
tests/001-long-text_a.mp3 tests/001-long-text_b.mp3 differ: byte 781, line 3
tests/001-long-text_a.mp3 tests/001-long-text_g.mp3 differ: byte 27425332, line 110673
tests/001-long-text_a.srt tests/001-long-text_g.srt differ: byte 177684, line 5505
tests/001-long-text_a.mp3 tests/001-long-text_h.mp3 differ: byte 27425332, line 110673
tests/001-long-text_a.mp3 tests/001-long-text_m.mp3 differ: byte 781, line 3
tests/001-long-text_a.mp3 tests/001-long-text_r.mp3 differ: byte 781, line 3
tests/001-long-text_a.srt tests/001-long-text_r.srt differ: byte 175768, line 5441
tests/001-long-text_a.mp3 tests/001-long-text_z.mp3 differ: byte 781, line 3
tests/001-long-text_a.srt tests/001-long-text_z.srt differ: byte 87159, line 2693
```

**Comment by rany2** [comment] 2024-05-17 13:26
> see if there is some sort of termination message

There isn't unfortunately :(

> Just with my timeout setting, the mp3 file is produced for 10 minutes and then it is finished uncomplete. when I chose smaller timeout values, in the beginning

Could you test the current version in master and see if you still get timeouts? The parameter now sets a timeout for socket recv, previously it was controlling the time it needs to get a websocket message response.

**Comment by rany2** [comment] 2024-05-18 10:32
@tschnibo yep, thank you. I just wanted to know that the timeout values in master are fine now.

**Comment by kovaacs** [comment] 2024-05-20 09:57
Just wondering, can the subtitles returned by the server used as a sanity check for data completeness? So, if the subtitles returned do not match the text sent, assume all data (including audio) to be incomplete. I haven't looked into it, but I can if you think it's not a stupid idea.

**Comment by rany2** [comment] 2024-05-20 10:25
@kovaacs It's not a stupid idea and I did consider it but the issue is that some characters are ignored by TTS depending on the voice selection (i.e., if you send Chinese characters to an English voice it will just ignore it; so the issue is that you need to somehow figure out all the values every voice takes)

**Comment by kovaacs** [comment] 2024-05-20 11:27
@rany2 I'm thinking maybe fuzzy matching could be an option. You compare the sent data with what was received, and see how similar they are. It could be an opt-in flag, e.g.`--min-confidence 0.8`, meaning if the the similarity is below 80%, consider the chunk a failure and retry it. It'd be up to the user to choose their similarity score and also to ensure that they don't send garbage data that would skew the score.

**Comment by rany2** [comment] 2024-05-20 11:31
@kovaacs Seems like it's more trouble than it's worth to be honest. I think as a workaround it would probably work but I'm not willing to implement it myself.

**Comment by rany2** [comment] 2024-05-21 10:30
I don't think it's that simple, it already divides the text into chunks and starts new sessions (new session or reusing old connection makes no diff); the issue is that I receive incomplete audio data from the service so I cannot be sure if the data is complete or not by just looking at whether there is audio or not.

Also the 5 minutes thing is not really reliable, I've had it happen in my test within 2 mins; the trouble is that it is inconsistent and there doesn't seem to be a pattern I could find.

**Comment by rany2** [comment] 2024-05-21 10:37
I think I've found a solution, it seems like an off-by-one error and the fix I initially tried would have worked; I'll keep you guys posted :')

**Comment by rany2** [comment] 2024-05-21 13:37
Please test https://github.com/rany2/edge-tts/commit/580f880bdaf34aced24f4badae8e025563eb2844

**Closed** 2024-05-21 13:37 UTC
Labels: help wanted

**Comment by kovaacs** [comment] 2024-05-21 21:52
@rany2 `n = 1`, but I've just exported a 14+ hour long file without problems. Thanks for fixing it so quickly, you saved me quite a lot of manual effort.

**Comment by mobad** [comment] 2024-06-01 22:02
@rany2 I'm working on a different Edge TTS client for Android and I'm running in to a similar issue where we intermittently receive   no data or timeout.
I was taking a look at your change https://github.com/rany2/edge-tts/commit/580f880bdaf34aced24f4badae8e025563eb2844 but I'm having a hard time seeing what the actual fix was.
It looks like it can better detect the incomplete audio and throw an exception but I don't see any retry mechanism. (Unless it's some python magic I'm missing)
Would it be possible for you be able to point out what the underlying issue was and what was the fix? Thanks!

**Comment by briankendall** [comment] 2024-06-24 21:13
Just popping in to say that this is indeed fixed. Thanks!

**Comment by wslyyy** [comment] 2024-07-19 03:19
> @rany2 I'm working on a different Edge TTS client for Android and I'm running in to a similar issue where we intermittently receive no data or timeout. I was taking a look at your change [580f880](https://github.com/rany2/edge-tts/commit/580f880bdaf34aced24f4badae8e025563eb2844) but I'm having a hard time seeing what the actual fix was. It looks like it can better detect the incomplete audio and throw an exception but I don't see any retry mechanism. (Unless it's some python magic I'm missing) Would it be possible for you be able to point out what the underlying issue was and what was the fix? Thanks!


@rany2 The same question

**Comment by rany2** [comment] 2024-07-19 19:57
@mobad @wslyyy without source code its hard to tell, but there are many factors that might cause this to happen. The annoying bit is that Microsoft does not return any errors but instead just silently fails either completely or for some chunks.

**Comment by thangckt** [comment] 2025-03-08 17:56
hi @rany2 

I get the mp3 file limit within 55 minutes, and the remain text is omitted.
Do you know why?

Thanks.

**Comment by rany2** [comment] 2025-03-08 18:01
@thangckt what edge-tts version are you using and does it raise any exception like NoAudioReceived?

**Comment by thangckt** [comment] 2025-03-08 18:06
Hi @rany2 

I install last ver on your default branch.

The process complished without error, and i can get mp3 file.

but sometime it has length more than 55 minutes while normally return mp3 cut at 55m.

**Comment by rany2** [comment] 2025-03-08 18:10
@thangckt Can you try to build master while modifying https://github.com/rany2/edge-tts/blob/master/src/edge_tts/communicate.py#L221C31-L221C36 such that `websocket_max_size` is something like `2**14`?

**Comment by thangckt** [comment] 2025-03-08 18:12
I will try and let you know.

Thanks.
