### ISSUE TITLE
edge_tts.exceptions.NoAudioReceived: No audio was received. Please verify that your parameters are correct.

### ISSUE THREAD

**Issue by kamimachi** [rany2/edge-tts#74] opened 2023-04-19 07:34 UTC
When I call the speech generation function multiple times with the code, I get the error:  **edge_tts.exceptions.NoAudioReceived: No audio was received. Please verify that your parameters are correct.**， last week all is ok， but today is have the error

**Comment by rany2** [comment] 2023-04-19 07:54
How are you calling it? Can you show code that has this issue? Maybe the voice you are using got deprecated

**Comment by syh-667** [comment] 2023-04-19 09:09
Mine is also this problem.  Sometimes it works, sometimes it doesn't.

**Comment by guoguozhang** [comment] 2023-04-19 09:35
edge_tts.exceptions.NoAudioReceived: No audio was received. Please verify that your parameters are correct.
Error: Command 'edge-tts --voice zh-CN-XiaoyiNeural --text "hello world" --write-media ./output/56EBE590-8671-457A-9299-D9453B52CB8F.mp3' returned non-zero exit status 1.

**Comment by rany2** [comment] 2023-04-19 09:55
@guoguozhang I'm not entirely sure what the issue is, but seems to be working reliably on my end. Perhaps their service is under some load/maintenance?

**Comment by guoguozhang** [comment] 2023-04-19 11:39
This command runs fine in the command line, but when executed by multiple threads in Python, it usually results in an error on Windows.

**Comment by rany2** [comment] 2023-04-19 11:39
@guoguozhang Then Microsoft increased their protections against abuse. That is the only explanation.

**Comment by kamimachi** [comment] 2023-04-19 12:49
> ###

When I receive a sentence, I split the sentence with commas and periods, divide the sentence into several paragraphs, and call the speech-generated function once each time I split. The purpose is to reduce the delay, and I can generate speech content while receiving sentences sent to me by others, rather than waiting for me to send them and then generate speech. 

This feature was completed last week and was tested without any issues. But when testing today, he made an error, when splitting the sentence, the first split content into the function is no problem, but immediately after the second speech into the speech generation function, there will be no reply, an error will appear. 


Eventually I replaced the original edge_tts package with a VITS model to generate speech.

**Comment by rany2** [comment] 2023-04-20 22:04
Is anyone still experiencing this issue? I can't trigger it and I've been running hundreds of threads in parallel just constantly launching TTS generations.

**Comment by rany2** [comment] 2023-04-24 09:55
I presume this issue no longer occurs or still relevant? @kamimachi @guoguozhang

**Comment by kamimachi** [comment] 2023-04-25 01:25
> I presume this issue no longer occurs or still relevant? @kamimachi @guoguozhang

Thank you very much for your reply, I just went to test the code that used edg_tts for speech generation before and found that there were no problems. But I decided to use the VITS model anyway because he is not prone to accidents.

**Comment by rany2** [comment] 2023-04-26 21:40
@kamimachi Fair enough, so I'll close this because it appears to have been a server issue on Microsoft's end.

**Closed by rany2** 2023-04-26 21:40 UTC

**Comment by asasas234** [comment] 2023-08-29 06:13
@rany2 I also encountered this problem. I plan to set up a new machine as a proxy. I'm not sure if it can solve the issue.

**Comment by xmnlab** [comment] 2023-08-30 01:19
I am also experiencing this error here ...

**Comment by xmnlab** [comment] 2023-08-30 10:54
In my case is English text,  and if I execute the same code again (like 1 second later), that works. It looks like a non-determiniatic error .. maybe some issue with the server, I don't know.

**Comment by yixian3500** [comment] 2023-12-27 02:56
I just got this problem for several times today ，just restart it to find if will be ok later
